### ISSUE TITLE
parenthesize argument(s) for future version

### ISSUE THREAD

**Issue by wereHamster** [floere/view_models#6]
Any chance to fix that in a point release?

view_models-2.0.0/lib/rails2/../shared/lib/view_models/base.rb:74: warning: parenthesize argument(s) for future version

**Comment by floere** [comment]
Hi Tomas

Absolutely. I hope to get to it soon.

Cheers

**Comment by floere** [comment]
Hi Tomas

It should be fixed.

Cheers
